import { BiiioProfile } from "./types";

export const mockProfile: BiiioProfile = {
  username: "alexmorgan",
  displayName: "Alex Morgan",
  bio: "Designer & creative director. Building beautiful things on the internet. ✦",
  avatarUrl: "https://i.pravatar.cc/300?img=47",
  accentColor: "#7C3AED",
  theme: "dark",
  socials: [
    { platform: "instagram", url: "https://instagram.com" },
    { platform: "tiktok", url: "https://tiktok.com" },
    { platform: "youtube", url: "https://youtube.com" },
    { platform: "x", url: "https://x.com" },
    { platform: "spotify", url: "https://spotify.com" },
  ],
  links: [
    {
      id: "1",
      type: "hero",
      title: "✦ New Course — Design Systems 101",
      url: "https://example.com/course",
      description: "Learn how to build scalable design systems from scratch. Enroll now →",
      active: true,
      clicks: 1420,
    },
    {
      id: "2",
      type: "link",
      title: "My Portfolio",
      url: "https://example.com/portfolio",
      description: "Selected projects & case studies",
      emoji: "🎨",
      active: true,
      clicks: 890,
    },
    {
      id: "3",
      type: "link",
      title: "Newsletter — Weekly Design Notes",
      url: "https://example.com/newsletter",
      description: "500+ subscribers. Every Tuesday.",
      emoji: "📬",
      active: true,
      clicks: 654,
    },
    {
      id: "4",
      type: "link",
      title: "Book a 1:1 Call",
      url: "https://cal.com",
      description: "30-min strategy session",
      emoji: "📅",
      active: true,
      clicks: 312,
    },
    {
      id: "5",
      type: "link",
      title: "Figma Templates Shop",
      url: "https://example.com/shop",
      description: "Premium UI kits & resources",
      emoji: "🛍",
      active: true,
      clicks: 278,
    },
    {
      id: "6",
      type: "link",
      title: "My YouTube Channel",
      url: "https://youtube.com",
      description: "Free design tutorials every week",
      emoji: "▶️",
      active: true,
      clicks: 198,
    },
  ],
};

export const mockAnalytics = {
  totalViews: 12500,
  totalClicks: 8200,
  ctr: 65.6,
  avgTime: "45s",
  viewsTrend: "+15%",
  clicksTrend: "+10%",
  ctrTrend: "+5%",
  avgTimeTrend: "-2%",
  topLink: "Design Systems 101",
  topSource: "Instagram",
  chartData: [
    { label: "Mar 01", views: 40, clicks: 0 },
    { label: "Mar 02", views: 55, clicks: 0 },
    { label: "Mar 03", views: 45, clicks: 0 },
    { label: "Mar 04", views: 70, clicks: 0 },
    { label: "Mar 05", views: 65, clicks: 0 },
    { label: "Mar 06", views: 0,  clicks: 30 },
    { label: "Mar 07", views: 85, clicks: 0 },
    { label: "Mar 08", views: 90, clicks: 0 },
    { label: "Mar 09", views: 0,  clicks: 45 },
    { label: "Mar 10", views: 75, clicks: 0 },
    { label: "Mar 11", views: 60, clicks: 0 },
    { label: "Mar 12", views: 80, clicks: 0 },
    { label: "Mar 13", views: 0,  clicks: 55 },
    { label: "Mar 14", views: 100, clicks: 0 },
  ],
  sources: [
    { name: "Instagram", value: 45, color: "#d2aef8" },
    { name: "TikTok",    value: 30, color: "#91cefb" },
    { name: "Twitter",   value: 15, color: "#f7d59e" },
    { name: "Direct",    value: 10, color: "#e2e2e2" },
  ],
  topLinks: [
    { title: "My Portfolio 2024", url: "biiio.io/alexmorgan/portfolio", clicks: 4200, icon: "🔗" },
    { title: "Digital Assets Store", url: "gumroad.com/alexmorgan", clicks: 2800, icon: "🛍️" },
    { title: "Newsletter Signup", url: "substack.com/alexmorgan", clicks: 1200, icon: "📬" },
  ],
  deviceSplit: { mobile: 82, desktop: 18 },
  topCountries: [
    { code: "USA", value: 5200 },
    { code: "UK",  value: 2100 },
    { code: "GER", value: 1800 },
  ],
};
